
control_bits:
  - AI
  - AO
  - BI
  - BO
  - ALO
  - ADD
  - SUB
  - II
  - MI
  - RI
  - RO
  - CE
  - JMP
  - CO
  - OI
  - IO


instructions:
  LDA:
    addr: 0
    steps:
      - [MI, IO]
      - [RO, AI]

  ADD:
    addr: 1
    steps:
      - [MI, IO]
      - [RO, BI]
      - [ADD, ALO, AI]

  OUT:
    addr: 2
    steps:
      - [AO, OI]

  STA:
    addr: 3
    steps:
      - [MI, IO]
      - [RI, AO]



